// TODO:
// Remove this utility when boggle boards are generated by server

import DICTIONARY from "./dictionary.js"

class Checker {
  static check(word) {
    return DICTIONARY.indexOf(word) > -1
  }
}

export default Checker
