// TODO:
// Remove this utility when boggle boards are generated by server

import DICTIONARY from "./dictionary.js"

class Checker {
  static check(word) {
    const wholeWord = " " + word.toLowerCase() + " "
    return DICTIONARY.indexOf(wholeWord) > -1
  }
}

export default Checker
