export const START_GAME              = "START_GAME"
export const START_SELECTING_LETTERS = "START_SELECTING_LETTERS"
export const ADD_LETTER              = "ADD_LETTER"
export const SUBMIT_WORD             = "SUBMIT_WORD"
export const END_GAME                = "END_GAME"
export const ADD_LETTER_KEYBOARD     = "ADD_LETTER_KEYBOARD"
export const SUBMIT_WORD_KEYBOARD    = "SUBMIT_WORD_KEYBOARD"
export const SERVER_ERROR            = "SERVER_ERROR"
